config/routes.rb
Rails.application.routes.draw do


  root 'users#signup'

  get 'itineraries/:id/invite', to: 'mandrill#invite_form', as: "invite_form"
  get 'itineraries/:id/invite/signup', to: 'users#join', as: "invite_signup"

  get '/test', to: 'mandrill#test_form', as: "test_form"
  post '/test', to: 'mandrill#test', as: "test"
  post '/emails', to: 'mandrill#email', as: "email"
  post 'itineraries/:id/invite', to: 'mandrill#test', as: "invite"
  post 'itineraries/:id/invite/signup', to: 'users#create', as: "invited_user_signup"

  get '/login', to: 'users#login', as: "login"
  get '/signup', to: 'users#signup', as: "signup"
  get '/home', to: 'users#home', as: "home"
  post '/signup', to: 'users#create', as: "users"
  post '/login', to: 'users#attempt_login', as: "attempt_login"
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/itineraries/:itinerary_id/activities/:activity_id/users', to: 'users#add_activity', as: 'new_itinerary_activity_user'
  delete '/itineraries/:itinerary_id/activities/:activity_id/users/:user_id', to: 'users#remove_activity', as: 'remove_itinerary_activity_user'
  post '/itineraries/:itinerary_id/users', to: 'users#add_itinerary', as: 'new_itinerary_user'
  delete '/itineraries/:itinerary_id/users/:user_id', to: 'users#remove_itinerary', as: 'remove_itinerary_user'

  post '/itineraries/:some_itinerary/activities/:activity_id/reviews' => 'reviews#create_review', as: 'itinerary_activity_reviews'

  resources :itineraries do
    post '/reviews' => 'reviews#create_review', as: 'reviews'
    resources :activities
  end

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  validates :origin, :destination, :name, :user_id, presence: true

  has_many :activities, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :itineraries_users
  has_many :users, through: :itineraries_users
  has_many :reviews, as: :reviewable

end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  before_action :find_itinerary, only: [:show, :edit, :update]

  def index
    @itineraries = User.find(session[:user_id]).itineraries
  end

  def new
    @itinerary = Itinerary.new
  end

  def show
    @itinerary_owner = User.find @itinerary.user_id
    @reviews = @itinerary.reviews
    # @users and @user are needed for add companion dropdown
    @users = User.all
    @user = User.new
  end

  def edit
    @itinerary_owner = User.find @itinerary.user_id
  end

  def create
    @itinerary = Itinerary.new itinerary_params
    if @itinerary.save
      @user = User.find(session[:user_id])
      @user.itineraries << @itinerary
      redirect_to itineraries_path
    else
      if session[:user_id] == nil
        flash.now[:alert] = "Please Login"
      else
        flash.now[:alert] = "Please correct the following input errors"
      end
      render :new
    end
  end

  def update
    @itinerary.update_attributes itinerary_params
    if @itinerary.save
      redirect_to itinerary_path(@itinerary)
    else
      flash.now[:alert] = "Please correct the following input errors"
      render :edit
    end
  end

  def destroy
    itinerary = Itinerary.find params[:id] # No need for instance var here #
    puts "session user_id #{session[:user_id]}"
    puts "itinerary user _id #{itinerary[:user_id]}"
    if session[:user_id] != itinerary[:user_id]
      flash[:alert] = "You are not authorized to delete this itinerary"
      redirect_to itineraries_path
    else
    itinerary.destroy
    redirect_to itineraries_path
    end
  end

  private

  def find_itinerary
    @itinerary = Itinerary.find params[:id]
  end

  def itinerary_params
    params.require(:itinerary).permit(:name, :origin, :destination, :departure_date, :return_date, :user_id)
  end

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_form.html.erb
<%= simple_form_for(@itinerary, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
<div class="row">
  <div class="col-md-2 col-md-offset-1">
    <%= f.input :name%>
  </div>
  <div class="col-md-2 col-md-offset-1">
    <%= f.input :origin%>
  </div>
  <div class="col-md-4 col-md-offset-1">
    <br>
    <%= f.input :departure_date%>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-2 col-md-offset-1">
    <%= f.input :user_id%>
  </div>
  <div class="col-md-2 col-md-offset-1">
    <%= f.input :destination%>
  </div>
  <div class="col-md-4 col-md-offset-1">
    <br>
    <%= f.input :return_date%>
  </div>
</div>
<br><br>
<div class ="row">
  <div class = "col-md-2 col-md-offset-3">
    <%=  link_to('Back to Itineraries', itineraries_path, {class: "btn btn-primary"}) %>
  </div>
  <div class ="col-md-2 col-md-offset-2">
    <%= f.submit "Create itinerary", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>
</div>

app/views/itineraries/edit.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container-fluid">
  <h2 class ="text-center">Edit Itinerary</h2>
  <br>

  <%= simple_form_for(@itinerary, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-group"}) do |f|%>
    <div class="row">
      <div class="col-md-3 col-md-offset-5">
        <%= f.input :name, label: "Itinerary Name:"%>
        <br>
      </div>
      <div class ="row">
        <div class="col-md-3 col-md-offset-3">
          <%= f.input :origin  %>
        </div>
        <div class="col-md-3 col-md-offset-1">
          <%= f.input :destination%>
        </div>
      </div>
      <br>
    <div class="row">
      <div class="col-md-3 col-md-offset-3">
        <%= f.input :departure_date%>
      </div>
      <div class="col-md-3 col-md-offset-1">
        <%= f.input :return_date%>
      </div>
    </div>
    <br><br>
    <div class ="row">
      <div class = "col-md-1 col-md-offset-3">
        <%= link_to('Cancel', itinerary_path(@itinerary), {class: "btn btn-primary"}) %>
      </div>
      <div class = "col-md-2 col-md-offset-3">
        <%= link_to('Delete Itinerary', itinerary_path(@itinerary), method: :delete, data: { confirm: "Are you sure? Deleting this itinerary will delete all corresponding acitivites and companions." }, class: "btn btn-danger")%>
      </div>
      <div class ="col-md-2">
        <%= f.submit "Save changes", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

</div>

app/views/itineraries/index.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container-fluid">
  <h2 class = "text-center">Itineraries</h2>
  <br>
  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-10 col-md-offset-1">
      <table class ="table table-striped">
        <tr>
          <th>Name</th>
          <th>Origin</th>
          <th>Destination</th>
          <th>Depart Date</th>
          <th>Return Date</th>
          <th>Owner</th>
          <th>Info</th>
          <th>Invite</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <% @itineraries.each do |itinerary| %>
        <tr >
          <td><%= itinerary.name  %></td>
          <td><%= itinerary.origin %></td>
          <td><%= itinerary.destination %></td>
          <td><%= itinerary.departure_date %></td>
          <td><%= itinerary.return_date %></td>
          <td><%= User.find(itinerary.user_id).username %></td>
          <td><%= link_to('Info', itinerary_path(itinerary), {class: "btn-xs btn-info"})%></td>
           <td><%= link_to('Invite', invite_form_path(itinerary), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Edit', edit_itinerary_path(itinerary), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Delete', itinerary_path(itinerary), method: :delete, data: { confirm: "Are you sure? Deleting this itinerary will delete all corresponding acitivites and companions." }, class: "btn-xs btn-danger")%></td>
        </tr>
        <%end %>
      </table>
    </div>
  </div>
  <br>
  <div class="row">
    <div class ="col-md-2 col-md-offset-1">
      <%=  link_to('Add new ', new_itinerary_path, {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/itineraries/new.html.erb
<%= render "shared/navbar" %>

<div class="container-fluid">
<br><br>
  <h2 class ="text-center">New Itinerary:</h2>
  <br>

  <%= simple_form_for(@itinerary, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-group"}) do |f|%>
  <div class="row">
    <div class="col-md-3 col-md-offset-5">
      <%= f.input :name, label: "Itinerary Name:"%>
    </div>
    </div>
    <br>
    <div class ="row">
    <div class="col-md-3 col-md-offset-3">
      <%= f.input :origin  %>
    </div>
    <div class="col-md-3 col-md-offset-1">
      <%= f.input :destination%>
    </div>
  </div>
  <br>
  <div class="row">
      <%= f.input :user_id, :as => :hidden, :input_html => { :value => session[:user_id] }%>
    <div class="col-md-4 col-md-offset-2">
      <%= f.input :departure_date%>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <%= f.input :return_date%>
    </div>
  </div>
  <br><br>
  <div class ="row">
    <div class = "col-md-2 col-md-offset-3">
      <%=  link_to('Back to Itineraries', itineraries_path, {class: "btn btn-primary"}) %>
    </div>
    <div class ="col-md-2 col-md-offset-2">
      <%= f.submit "Create itinerary", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>

</div>

app/views/itineraries/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
<br>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><p><%=  link_to('Back to Itineraries', itineraries_path, {class: "btn btn-primary"}) %></p></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p><%= link_to('Home',itineraries_path, class: "btn btn-primary")%></p></li>
          <% if session[:first_name] != nil %>
        <li><p><%= link_to('Logout',logout_path, method: :delete,  class: "btn btn-primary")%></p></li>
        <% else %>
          <li><p><%= link_to('Login',login_path,  class: "btn btn-primary")%></p></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br>
<div class="container-fluid">
  <h2 class = "text-center"> <%= @itinerary.name%> </h2>
  <br>
  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-8 col-md-offset-2">
      <table class ="table table-striped">
        <tr>
          <th>Name</th>
          <th>Origin</th>
          <th>Destination</th>
          <th>Depart Date</th>
          <th>Return Date</th>
          <th>Activities</th>
          <th>Owner</th>
          <th>Edit</th>
        </tr>
        <tr>
          <td><%= @itinerary.name %></td>
          <td><%= @itinerary.origin %></td>
          <td><%= @itinerary.destination %></td>
          <td><%= @itinerary.departure_date %></td>
          <td><%= @itinerary.return_date %></td>
          <td><%= link_to('See Activities', itinerary_activities_path(@itinerary), {class: "btn-xs btn-info"}) %></td>
          <td><%= @itinerary_owner.username %></td>
          <td><%= link_to('Edit', edit_itinerary_path(@itinerary), {class: "btn-xs btn-info"})%></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class ="col-md-6">
      <h3 class="text-center">Companions</h3>
    </div>
    <div class ="col-md-6">
      <h3 class="text">Comments</h3>
    </div>
  </div>
  <% if session[:user_id] == @itinerary.user_id %>
    <div class="row">
      <div class ="col-md-4 col-md-offset-2">
        <%= form_for @user, url: new_itinerary_user_path(@itinerary) do |f| %>
          <%= f.label :id, "Add a companion: " %>
          <%= f.text_field :id, list: "users" %>
          <datalist id="users">
            <% @users.each do |user| %>
            <% unless @itinerary.user_id == user.id %>
              <option value=<%= user.id %>><%= user.first_name %> <%= user.last_name %></option>
            <% end %>
            <% end %>
          </datalist>
          <%= f.submit 'Add' %>
        <% end %>
        <br>
      </div>
      <div class ="col-md-6">
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class ="col-md-4 col-md-offset-2">
      <table class ="table table-striped">
        <% @itinerary.users.each do |user| %>
          <tr>
            <td><%= user.first_name %> <%= user.last_name %></td>
            <% if @itinerary.user_id == session[:user_id] %>
            <% unless @itinerary.user_id == user.id %>
              <!-- double-check below -->
              <td><%= link_to('Remove', remove_itinerary_user_path(@itinerary, user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
            <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
    <div class ="col-md-6">
      <%= form_for [@itinerary, Review.new] do |f| %>
        <div>
          <%= f.text_area :content, :rows => 3, :cols => 50 %>
        </div>
        <%= f.submit "Add comment" %>
      <% end %>
      <br>
      <% @reviews.each do |review| %>
        <p>
          <%= review.content %> - <%= time_ago_in_words review.created_at %> ago by <strong><%= User.find(review.user_id).username %></strong>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/itineraries/temp.html.erb
          <td><%= link_to('Info', movie_path(movie), {class: "btn-xs btn-info"})%></td>
          <td><%= link_to('Edit', edit_movie_path(movie), {class: "btn-xs btn-info"})%></td>