config/routes.rb
Rails.application.routes.draw do


  root 'users#signup'

  get 'itineraries/:id/invite', to: 'mandrill#invite_form', as: "invite_form"
  get 'itineraries/:id/invite/signup', to: 'users#join', as: "invite_signup"

  get '/test', to: 'mandrill#test_form', as: "test_form"
  post '/test', to: 'mandrill#test', as: "test"
  post '/emails', to: 'mandrill#email', as: "email"
  post 'itineraries/:id/invite', to: 'mandrill#test', as: "invite"
  post 'itineraries/:id/invite/signup', to: 'users#create', as: "invited_user_signup"

  get '/login', to: 'users#login', as: "login"
  get '/signup', to: 'users#signup', as: "signup"
  get '/home', to: 'users#home', as: "home"
  post '/signup', to: 'users#create', as: "users"
  post '/login', to: 'users#attempt_login', as: "attempt_login"
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/itineraries/:itinerary_id/activities/:activity_id/users', to: 'users#add_activity', as: 'new_itinerary_activity_user'
  delete '/itineraries/:itinerary_id/activities/:activity_id/users/:user_id', to: 'users#remove_activity', as: 'remove_itinerary_activity_user'
  post '/itineraries/:itinerary_id/users', to: 'users#add_itinerary', as: 'new_itinerary_user'
  delete '/itineraries/:itinerary_id/users/:user_id', to: 'users#remove_itinerary', as: 'remove_itinerary_user'

  post '/itineraries/:some_itinerary/activities/:activity_id/reviews' => 'reviews#create_review', as: 'itinerary_activity_reviews'

  resources :itineraries do
    post '/reviews' => 'reviews#create_review', as: 'reviews'
    resources :activities
  end

end

app/controllers/mandrill_controller.rb
class MandrillController < ApplicationController
def test_form
@invite = Invite.new
end

def email 
  binding.pry

end

def invite_form
@invite =Invite.new
end

require 'mandrill'
mandrill = Mandrill::API.new ENV["MANDRIL_APIKEY"]

def test
call
end


def call
emails = invite_params[:email].split
@itinerary = Itinerary.find(params[:id])
inviter_name = session[:first_name]
binding.pry
require 'mandrill'
m = Mandrill::API.new 
message = {  
 :subject=> "#{inviter_name} has invited you to join #{@itinerary.name}!",  
 :from_name=> "#{@itinerary.name}",  
 :text=>"#{inviter_name} has invited you to join #{@itinerary.name}!",  
 :to=> emails.map {|email|{email:email,name:"Friend"}},

 :html=>"<html><h1>Your friend, #{inviter_name}, has invited you to join their itinerary: #{@itinerary.name}. <a href='https://desolate-shelf-9091.herokuapp.com/itineraries/#{params[:id]}/invite/signup'>Join Now!</a> </h1></html>",  
 :from_email=>"gannavas@gmail.com"  
}  
binding.pry
sending = m.messages.send message  
puts sending
redirect_to itineraries_path
end
private
  def invite_params
    params.require(:invite).permit(:itinerary_id, :email)
  end
end

app/helpers/mandrill_helper.rb
module MandrillHelper
end

app/views/mandrill/invite_form.html.erb
<%= render "shared/navbar" %>

<div class="container-fluid">
<br><br>
  <h2 class ="text-center">Invite Friends:</h2>
  <br>
  <p class = "text-center">*separate email with space*</p>

   <%= form_for(@invite,url: invite_form_path, method: :post) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
    <%= f.text_area :email, :rows => 10, :cols => 150 %>
    </div>
    </div>
    <Br>
    <div class = "col-md-2 col-md-offset-5">
    <%= f.submit "Email Friends" %>
    <div>
  <% end %>

</div>

app/views/mandrill/test_form.html.erb
<%=link_to( "test", '/test', method: :post) %>

<%= form_tag("/emails", method: "post") do %>
  <%= label_tag(:email, "Search for:") %>
  <%= text_field_tag(:email) %>
  <%= submit_tag("Search") %>
<% end %>
<div class = "container-fluid">
 <%= form_for(@invite,url: test_path, method: :post) do |f| %>
        <div>
          <%= f.text_area :email, :rows => 3, :cols => 50 %>
        </div>
        <%= f.submit "Add Emails" %>
      <% end %>

</div>