config/routes.rb
Rails.application.routes.draw do


  root 'users#signup'

  get 'itineraries/:id/invite', to: 'mandrill#invite_form', as: "invite_form"
  get 'itineraries/:id/invite/signup', to: 'users#join', as: "invite_signup"

  get '/test', to: 'mandrill#test_form', as: "test_form"
  post '/test', to: 'mandrill#test', as: "test"
  post '/emails', to: 'mandrill#email', as: "email"
  post 'itineraries/:id/invite', to: 'mandrill#test', as: "invite"
  post 'itineraries/:id/invite/signup', to: 'users#create', as: "invited_user_signup"

  get '/login', to: 'users#login', as: "login"
  get '/signup', to: 'users#signup', as: "signup"
  get '/home', to: 'users#home', as: "home"
  post '/signup', to: 'users#create', as: "users"
  post '/login', to: 'users#attempt_login', as: "attempt_login"
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/itineraries/:itinerary_id/activities/:activity_id/users', to: 'users#add_activity', as: 'new_itinerary_activity_user'
  delete '/itineraries/:itinerary_id/activities/:activity_id/users/:user_id', to: 'users#remove_activity', as: 'remove_itinerary_activity_user'
  post '/itineraries/:itinerary_id/users', to: 'users#add_itinerary', as: 'new_itinerary_user'
  delete '/itineraries/:itinerary_id/users/:user_id', to: 'users#remove_itinerary', as: 'remove_itinerary_user'

  post '/itineraries/:some_itinerary/activities/:activity_id/reviews' => 'reviews#create_review', as: 'itinerary_activity_reviews'

  resources :itineraries do
    post '/reviews' => 'reviews#create_review', as: 'reviews'
    resources :activities
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :first_name, :last_name, presence: true
  has_many :itineraries_users
  has_many :itineraries, through: :itineraries_users 
  has_many :activities_users
  has_many :activities, through: :activities_users 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user_form, only: [:add_itinerary, :add_activity]
  before_action :find_user_route, only: [:remove_itinerary, :remove_activity]
  before_action :find_itinerary, only: [:add_itinerary, :remove_itinerary, :add_activity, :remove_activity]
  before_action :find_activity, only: [:add_activity, :remove_activity]

  def login
    @user = User.new
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      if params[:id] == nil
        redirect_to login_path
      else
        @itinerary = Itinerary.find(params[:id])
        @itinerary.users << @user
        @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        session[:username] = @user.username
        session[:first_name] = @user.first_name
        flash[:notice] = "Welcome #{@user.first_name}"
        redirect_to itinerary_path(params[:id])
      end
    else
      flash.now[:notice] = "Please try again!!"
      if params[:id] == nil
        render :signup
      else
        render :join
      end
    end
  end

  def attempt_login
    if User.exists?(username: user_params[:username])
      @user = User.find_by(username: user_params[:username])
      if @user.authenticate(user_params[:password])
        session[:user_id] = @user.id
        session[:username] = @user.username
        session[:first_name] = @user.first_name
        flash[:notice] = "Welcome #{@user.first_name}"
        if session[:itinerary_id] == nil
          redirect_to itineraries_path
           session[:itinerary_id] == nil
        else
          redirect_to itinerary_path(session[:itinerary_id])
        end
      else
        flash[:notice] = "Incorrect Password"
        redirect_to login_path
      end
    else
      flash[:notice] = "Username not found"
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    session[:first_name] = nil
    session[:itinerary_id] =nil
    flash[:notice] = "You are now logged out."
    redirect_to login_path
  end

  def add_itinerary
    @itinerary.users << @user
    redirect_to itinerary_path(@itinerary)
  end

  def remove_itinerary
    @itinerary.users.delete(@user)
    redirect_to itinerary_path(@itinerary)
  end

  def add_activity
    @activity.users << @user
    redirect_to itinerary_activity_path(@itinerary, @activity)
  end

  def remove_activity
    @activity.users.delete(@user)
    redirect_to itinerary_activity_path(@itinerary, @activity)
  end

  def join
    session[:itinerary_id] = params[:id]
    @user = User.new
    @itinerary = Itinerary.find(params[:id])
  end

private

  def find_user_form
    # this gets the id from the simple_form
    @user = User.find params[:user][:id]
  end

  def find_user_route
    # this gets the id from the simple_form
    @user = User.find params[:user_id]
  end

  def find_itinerary
    @itinerary = Itinerary.find params[:itinerary_id]
  end

  def find_activity
    @activity = Activity.find params[:activity_id]
  end

  def user_params
    params.require(:user).permit(:id, :username, :password, :email, :first_name, :last_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render "shared/navbar" %>
<Br>
<div class="container-fluid">
 <div class ="row">
    <div class ="col-md-2 col-md-offset-11">
     <%=  link_to('Sign in!', login_path, {class: "btn-lg btn-info"}) %>
    </div>
  </div>
<br><br>
  <h2 class ="text-center">Create an account:</h2>
  <br>

  <%= simple_form_for(@user, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <%= f.input :first_name%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :last_name%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :username%>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <%= f.input :email%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :password%>
    </div>
  </div>
  <br><br>
  <div class ="row">
    <div class ="col-md-2 col-md-offset-5">
      <%= f.submit "Create account", class: 'btn-lg btn-primary' %>
    </div>
  </div>
  <% end %>

</div>

app/views/users/home.html.erb
<h1>Users#home</h1>
<p>Find me in app/views/users/home.html.erb</p>

app/views/users/join.html.erb
<div class="container-fluid">
<br><br>
  <h2 class ="text-center">Create an account to join <%=@itinerary.name %>:</h2>
  <br>

  <%= simple_form_for(@user, url: invited_user_signup_path, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <%= f.input :first_name%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :last_name%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :username%>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <%= f.input :email%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :password%>
    </div>
  </div>
  <br><br>
  <div class ="row">
    <div class ="col-md-2 col-md-offset-5">
      <%= f.submit "Join #{@itinerary.name} ", class: 'btn-lg btn-primary' %>
    </div>
  </div>
  <% end %>
  <Br><Br><Br>
  <p class="text-center"> Already signed up? </p>

    <%= simple_form_for(@user,url: attempt_login_path(params[:id]), defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
  <div class="row">
    <div class="col-md-2 col-md-offset-4">
      <%= f.input :username%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :password%>
    </div>
  </div>
  <br><br>
  <div class ="row">
    <div class ="col-md-2 col-md-offset-5">
      <%= f.submit "Login to Join #{@itinerary.name} ", class: 'btn-lg btn-primary' %>
    </div>
  </div>
  <% end %>

</div>

app/views/users/login.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">
<br><br>
  <h2 class ="text-center">Log In:</h2>
  <br>

  <%= simple_form_for(@user, :url => attempt_login_path, defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline-lg"}) do |f|%>
 
  <div class="row">
    <div class="col-md-2 col-md-offset-3">
      <%= f.input :username%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :password%>
    </div>
 </div>
 <div class = "row">
    <div class ="col-md-2 col-md-offset-5">
      <%= f.submit "Login", class: 'btn-lg btn-primary' %>
    </div>
    </div>
  <% end %>

</div>

app/views/users/signup.html.erb
<%= render "shared/navbar" %>
<%= render "form" %>