config/routes.rb
Rails.application.routes.draw do


  root 'users#signup'

  get 'itineraries/:id/invite', to: 'mandrill#invite_form', as: "invite_form"
  get 'itineraries/:id/invite/signup', to: 'users#join', as: "invite_signup"

  get '/test', to: 'mandrill#test_form', as: "test_form"
  post '/test', to: 'mandrill#test', as: "test"
  post '/emails', to: 'mandrill#email', as: "email"
  post 'itineraries/:id/invite', to: 'mandrill#test', as: "invite"
  post 'itineraries/:id/invite/signup', to: 'users#create', as: "invited_user_signup"

  get '/login', to: 'users#login', as: "login"
  get '/signup', to: 'users#signup', as: "signup"
  get '/home', to: 'users#home', as: "home"
  post '/signup', to: 'users#create', as: "users"
  post '/login', to: 'users#attempt_login', as: "attempt_login"
  delete '/logout', to: 'users#logout', as: 'logout'

  post '/itineraries/:itinerary_id/activities/:activity_id/users', to: 'users#add_activity', as: 'new_itinerary_activity_user'
  delete '/itineraries/:itinerary_id/activities/:activity_id/users/:user_id', to: 'users#remove_activity', as: 'remove_itinerary_activity_user'
  post '/itineraries/:itinerary_id/users', to: 'users#add_itinerary', as: 'new_itinerary_user'
  delete '/itineraries/:itinerary_id/users/:user_id', to: 'users#remove_itinerary', as: 'remove_itinerary_user'

  post '/itineraries/:some_itinerary/activities/:activity_id/reviews' => 'reviews#create_review', as: 'itinerary_activity_reviews'

  resources :itineraries do
    post '/reviews' => 'reviews#create_review', as: 'reviews'
    resources :activities
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :location, :name, :date, presence: true
  belongs_to :itinerary
  has_many :activities_users
  has_many :users, through: :activities_users
  has_many :reviews, as: :reviewable

  validates :date,
          date: { after_or_equal_to: :start_date, message: 'stop being a dick - activity date must be during the trip' }
  
  validates :date,
          date: { before_or_equal_to: :end_date, message: 'stop being a dick - activity date must be during the trip'}
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :find_itinerary, only: [:index, :new, :show, :edit, :create, :update]
  before_action :find_activity, only: [:edit, :update, :show, :destroy]

  def index
    @activities = @itinerary.activities
  end

  def new
    @activity = Activity.new
  end

  def show
    @itinerary_owner = User.find @itinerary.user_id
    @reviews = @activity.reviews
    # below necessary for companion dropdown
    @users = User.all
    @user = User.new
  end

  def edit
  end

  def create
    @activity = Activity.new activity_params
    # add the itinerary owner to the activity companion list
    @user = User.find session[:user_id]
    @activity.users << @user
    if @activity.save
      redirect_to itinerary_activities_path(@itinerary)
    else
      flash.now[:alert] = "Please correct the following input errors"
      render :new
    end
  end

  def update
    @activity.update_attributes activity_params
    if @activity.save
      redirect_to itinerary_activity_path(@itinerary, @activity)
    else
      flash.now[:alert] = "Please correct the following input errors"
      render :edit
    end
  end

  def destroy
    # Note: The instance variables are both needed for redirection
    #   (defined in before_action above)
    itinerary = Itinerary.find params[:itinerary_id]
    if session[:user_id] != itinerary[:user_id]
      puts "session user_id #{session[:user_id]}"
      puts "itinerary user _id #{itinerary[:user_id]}"
      flash[:alert] = "You are not authorized to delete this activity"
      redirect_to itinerary_activities_path(itinerary, @activity)
    else
      puts "session user_id #{session[:user_id]}"
      puts "itinerary user _id #{itinerary[:user_id]}"
      @activity.destroy
      redirect_to itinerary_activities_path(itinerary)
    end
  end

  private

  def find_itinerary
    @itinerary = Itinerary.find params[:itinerary_id]
  end

  def find_activity
    @activity = Activity.find params[:id]
  end

  def activity_params
    params.require(:activity).permit(:name, :location, :date, :itinerary_id, :start_date, :end_date)
  end



end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container-fluid">
  <h2 class ="text-center">Edit Activity</h2>
  <br>
  <%= simple_form_for(@activity, url: itinerary_activity_path(@itinerary, @activity), defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
  <div class="row">
    <div class="col-md-1 col-md-offset-3">
      <%= f.input :name%>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <%= f.input :location%>
    </div>
    <div class="col-md-4">
      <br>
      <%= f.input :date%>
    </div>
    <!-- hidden input -->
    <%= f.input :start_date, :as => :hidden, :input_html => { :value => @itinerary.departure_date }%>
      <%= f.input :end_date, :as => :hidden, :input_html => { :value => @itinerary.return_date }%>
  </div>
  <br><br>
  <div class ="row">
    <div class = "col-md-1 col-md-offset-3">
      <%= link_to('Cancel', itinerary_activities_path(@itinerary), {class: "btn btn-primary"}) %>
    </div>
    <div class = "col-md-2 col-md-offset-2">
      <%= link_to('Delete Activity', itinerary_activity_path(@itinerary, @activity), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger")%>
    </div>
    <div class ="col-md-2">
      <%= f.submit "Save changes", class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>

</div>

app/views/activities/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
<br>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><p><%=  link_to('Back to Itinerary', itinerary_path(@itinerary), {class: "btn btn-primary"}) %></p></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p><%= link_to('Home',itineraries_path, class: "btn btn-primary")%></p></li>
          <% if session[:first_name] != nil %>
        <li><p><%= link_to('Logout',logout_path, method: :delete,  class: "btn btn-primary")%></p></li>
        <% else %>
          <li><p><%= link_to('Login',login_path,  class: "btn btn-primary")%></p></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br>
<div class="container-fluid">
  <h2 class = "text-center">Activities for Itinerary: <%= @itinerary.name %></h2>
  <br>
  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-10 col-md-offset-1">
      <table class ="table table-striped">
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Date</th>
          <th>Info</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.name %></td>
            <td><%= activity.location %></td>
            <td><%= activity.date %></td>
            <td><%= link_to('Info', itinerary_activity_path(@itinerary, activity), {class: "btn-xs btn-info"})%></td>
            <td><%= link_to('Edit', edit_itinerary_activity_path(@itinerary, activity), {class: "btn-xs btn-info"})%></td>
            <td><%= link_to('Delete', itinerary_activity_path(@itinerary, activity), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <br>
  <div class="row">
    <div class ="col-md-2 col-md-offset-1">
      <%= link_to('Add new activity', new_itinerary_activity_path(@itinerary), {class: "btn btn-primary"}) %>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<%= render "shared/navbar" %>
<br>
<div class="container-fluid">
  <h2 class ="text-center">New Activity</h2>
  <br>
  <%= simple_form_for(@activity, url: itinerary_activities_path(@itinerary), defaults: { error_html: { id: 'error' } }, :html => { :class => "form-inline"}) do |f|%>
    <div class="row">
      <div class="col-md-1 col-md-offset-3">
        <%= f.input :name %>
      </div>
      <div class="col-md-2 col-md-offset-1">
        <%= f.input :location %>
      </div>
      <div class="col-md-4">
        <br>
        <%= f.input :date %>
      </div>
      <!-- hidden input -->
      <%= f.input :itinerary_id, :as => :hidden, :input_html => { :value => @itinerary.id }%>
      <%= f.input :start_date, :as => :hidden, :input_html => { :value => @itinerary.departure_date }%>
      <%= f.input :end_date, :as => :hidden, :input_html => { :value => @itinerary.return_date }%>
    </div>
    <br>
    <div class ="row">
      <div class = "col-md-2 col-md-offset-3">
        <%= link_to('Back to Activities', itinerary_activities_path(@itinerary), {class: "btn btn-primary"}) %>
      </div>
      <div class ="col-md-2 col-md-offset-2">
        <%= f.submit "Create Activity", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
<br>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <%= link_to('Back to Activities', itinerary_activities_path(@itinerary), {class: "btn btn-primary"}) %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p><%= link_to('Home',itineraries_path, class: "btn btn-primary")%></p></li>
          <% if session[:first_name] != nil %>
        <li><p><%= link_to('Logout',logout_path, method: :delete,  class: "btn btn-primary")%></p></li>
        <% else %>
          <li><p><%= link_to('Login',login_path,  class: "btn btn-primary")%></p></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br>
<div class="container-fluid">
  <h2 class = "text-center"> <%= @activity.name%> </h2>
  <br>
  <!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
  <div class="row">
    <div class ="col-md-8 col-md-offset-2">
      <table class ="table table-striped">
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Date</th>
          <th>Owner</th>
        </tr>
        <tr>
          <td><%= @activity.name %></td>
          <td><%= @activity.location %></td>
          <td><%= @activity.date %></td>
          <td><%= @itinerary_owner.username %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class ="col-md-6">
      <h3 class="text-center">Companions</h3>
    </div>
    <div class ="col-md-6">
      <h3 class="text">Comments</h3>
    </div>
  </div>
  <% if session[:user_id] == @itinerary.user_id %>
    <div class="row">
      <div class ="col-md-4 col-md-offset-2">
        <%= form_for @user, url: new_itinerary_activity_user_path(@itinerary, @activity) do |f| %>
          <%= f.label :id, "Add a companion: " %>
          <%= f.text_field :id, list: "users" %>
          <datalist id="users">
            <% @users.each do |user| %>
            <% unless @itinerary.user_id == user.id %>
              <option value=<%= user.id %>><%= user.first_name %> <%= user.last_name %></option>
            <% end %>
            <% end %>
          </datalist>
          <%= f.submit 'Add' %>
        <% end %>
        <br>
      </div>
      <div class ="col-md-6">
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class ="col-md-4 col-md-offset-2">
      <table class ="table table-striped">
        <% @activity.users.each do |user| %>
          <tr>
            <td><%= user.first_name %> <%= user.last_name %></td>
            <% if session[:user_id] == @itinerary.user_id %>
              <% unless @itinerary.user_id == user.id %>
              <td><%= link_to('Remove', remove_itinerary_activity_user_path(@itinerary, @activity, user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
            <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
    <div class ="col-md-6">
      <%= form_for [@itinerary, @activity, Review.new] do |f| %>
        <div>
          <%= f.text_area :content, :rows => 3, :cols => 50 %>
        </div>
        <%= f.submit "Add comment" %>
      <% end %>
      <br>
      <% @reviews.each do |review| %>
        <p>
          <%= review.content %> - <%= time_ago_in_words review.created_at %> ago by <strong><%= User.find(review.user_id).username %></strong>
        </p>
      <% end %>
    </div>
  </div>
  <br>
</div>